services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Krishan@150
      MYSQL_DATABASE: qp_assessment_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: Krishan@150
      DB_NAME: qp_assessment_db
    ports:
      - "5000:5000"

volumes:
  mysql-data:
